# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(False)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(30, 160, 201, 31))
        self.btn_generate.setStyleSheet("border-radius: 10px;\n"
"background: #fbeee0;\n"
"border: 2px solid #422800;\n"
"color: #00000")
        self.btn_generate.setAutoDefault(False)
        self.btn_generate.setObjectName("btn_generate")
        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(70, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(40, 70, 111, 21))
        self.label_password.setObjectName("label_password")
        self.cb_number = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_number.setGeometry(QtCore.QRect(40, 100, 161, 21))
        self.cb_number.setObjectName("cb_number")
        self.cb_alfabet = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_alfabet.setGeometry(QtCore.QRect(40, 130, 151, 16))
        self.cb_alfabet.setObjectName("cb_alfabet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 263, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_generate.setText(_translate("MainWindow", "Сгенерувати"))
        self.text.setText(_translate("MainWindow", "Генератор паролів"))
        self.label_password.setText(_translate("MainWindow", "Тут буде результат"))
        self.cb_number.setText(_translate("MainWindow", "Використовувати числа"))
        self.cb_alfabet.setText(_translate("MainWindow", "Використовувати алвавіт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
